import base64
import json
from email.mime.text import MIMEText
from typing import Any, Dict, List

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

from app.core.config import get_settings


def _get_gmail_service():
    settings = get_settings()
    creds_json = json.loads(base64.b64decode(settings.gmail_credentials_json).decode())
    creds = Credentials.from_authorized_user_info(creds_json)
    return build("gmail", "v1", credentials=creds)


class GmailClient:
    def send_action_items(
        self,
        to_email: str,
        owner_name: str,
        meeting_title: str,
        items: List[Dict[str, Any]],
    ) -> None:
        service = _get_gmail_service()
        lines = [f"Hi {owner_name},\n\nYour action items from '{meeting_title}':\n"]
        for item in items:
            deadline = item.get("deadline") or "No deadline"
            flag = " [NEEDS REVIEW]" if item.get("needs_review") else ""
            lines.append(f"- {item['task']} (by {deadline}){flag}")
        lines.append("\n\nGenerated by sync_ai.")
        message = MIMEText("\n".join(lines))
        message["to"] = to_email
        message["subject"] = f"Action Items: {meeting_title}"
        raw = base64.urlsafe_b64encode(message.as_bytes()).decode()
        service.users().messages().send(userId="me", body={"raw": raw}).execute()
