import base64
from email.mime.text import MIMEText
from typing import Any, Dict, List, Optional

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build


class GmailClient:
    def __init__(
        self,
        access_token: str,
        refresh_token: str,
        client_id: str,
        client_secret: str,
        token_uri: str = "https://oauth2.googleapis.com/token",
    ):
        creds = Credentials(
            token=access_token,
            refresh_token=refresh_token,
            token_uri=token_uri,
            client_id=client_id,
            client_secret=client_secret,
        )
        self._service = build("gmail", "v1", credentials=creds)

    def send_action_items(
        self,
        to_email: str,
        owner_name: str,
        meeting_title: str,
        items: List[Dict[str, Any]],
    ) -> None:
        lines = [f"Hi {owner_name},\n\nYour action items from '{meeting_title}':\n"]
        for item in items:
            deadline = item.get("deadline") or "No deadline"
            flag = " [NEEDS REVIEW]" if item.get("needs_review") else ""
            lines.append(f"- {item['task']} (by {deadline}){flag}")
        lines.append("\n\nGenerated by sync_ai.")
        message = MIMEText("\n".join(lines))
        message["to"] = to_email
        message["subject"] = f"Action Items: {meeting_title}"
        raw = base64.urlsafe_b64encode(message.as_bytes()).decode()
        self._service.users().messages().send(userId="me", body={"raw": raw}).execute()
